version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rccar
      MYSQL_DATABASE: rccar_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpw
      TZ: "Asia/Seoul"

    command:
      - --lower-case-table-names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
