spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/rccar_db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=UTC
    username: user
    password: userpw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret : a83917a28e96856d19bb44a813c5900a4b73f2bba388a4eaff9797127808e916